steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gcloud secrets versions access latest --secret=firebaseconfig --format='get(payload.data)' | tr '_-' '/+' | base64 -d > .env" ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/yen-sakiika:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/yen-sakiika:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: 
  - 'run'
  - 'deploy'
  - '$PROJECT_ID'
  - '--image'
  - 'gcr.io/$PROJECT_ID/yen-sakiika:$COMMIT_SHA'
  - 'region'
  - 'asia-northeast1-a'
  - '--platform'
  - 'managed'
images:
- 'gcr.io/$PROJECT_ID/yen-sakiika'
